### ISSUE TITLE
Mark down issue

### ISSUE THREAD

**Issue by brown-a2** [ministryofjustice/intranet#63]
Relating to the issue Dianne raised. Mark down issues have in the past been caused by WP plugin DW Markdown or our Draft plugin and the process in which the editor saves the page.

**Comment by tatyree** [comment]
A few weeks back, I met up with Dianne and she explained the steps to reproduce:

1. Go to page that used default template
1. Change value of `order` field
1. Save
1. At this point, the markdown will become HTML. 

I have been unable to reproduce this as yet.  She could not cause it to happen on the day.

**Comment by brown-a2** [comment]
I've had a go trying to recreate this, various ways on different browsers and using the above suggested procedure with no success. I may have to schedule another session with Di or another editor and try going through it with them again and recreating it.

**Comment by brown-a2** [comment]
Replaced markdown plugin with new plugin. Resolved issue.
